# Source: tekton-chains/templates/ClusterRoleBinding-tekton-chains-controller-cluster-access.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-chains-cluster
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "devel"
    version: "v0.8.0"
    gitops.jenkins-x.io/pipeline: 'cluster'
  annotations:
    meta.helm.sh/release-name: 'tekton-chains'
subjects:
- kind: ServiceAccount
  name: tekton-chains-controller
  namespace: tekton-chains
roleRef:
  kind: ClusterRole
  name: tekton-chains-cluster
  apiGroup: rbac.authorization.k8s.io
