# Source: tekton-chains/templates/ClusterRoleBinding-tekton-chains-controller-tenant-access.yml
# If this ClusterRoleBinding is replaced with a RoleBinding
# then the ClusterRole would be namespaced. The access described by
# the tekton-pipelines-controller-tenant-access ClusterRole would
# be scoped to individual tenant namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-chains-tenant
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "devel"
    version: "v0.8.0"
    gitops.jenkins-x.io/pipeline: 'cluster'
  annotations:
    meta.helm.sh/release-name: 'tekton-chains'
subjects:
- kind: ServiceAccount
  name: tekton-chains-controller
  namespace: tekton-chains
roleRef:
  kind: ClusterRole
  name: tekton-chains-tenant
  apiGroup: rbac.authorization.k8s.io
